name: Release

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install \
          libasound2-dev \
          libgl1-mesa-dev \
          libjack-dev \
          libx11-dev \
          libx11-xcb-dev \
          libxcb-dri2-0-dev \
          libxcb-icccm4-dev \
          libxcursor-dev \
          libxss-dev

      - name: Build
        run: cargo xtask bundle beatrec --release

  release-please:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.BEATREC_PAT }}
          release-type: rust

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.BEATREC_PAT }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./target/bundled/beatrec.clap ./target/bundled/beatrec.vst3
