name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PKG_CONFIG_PATH: /usr/lib/pkgconfig

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install libxss-dev libx11-dev

      - name: Build
        run: cargo xtask bundle beatrec --release
