name: Upload artifacts

on:
  push:
    branches:
      - main
    tags: ["v*"]

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: Beatrec

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - name: linux-x86_64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # - name: win-x86_64
          #   runner: windows-latest
          #   target: x86_64-pc-windows-msvc
          # - name: macos-x86_64
          #   runner: macos-latest
          #   target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Install system dependencies (Linux)
        if: ${{ matrix.name == 'linux-x86_64' }}
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install \
          libasound2-dev \
          libgl1-mesa-dev \
          libjack-dev \
          libx11-dev \
          libx11-xcb-dev \
          libxcb-dri2-0-dev \
          libxcb-icccm4-dev \
          libxcursor-dev \
          libxss-dev

      - name: Build
        run: cargo xtask bundle beatrec --release --target ${{ matrix.target }}

      - name: Zip macOS ARM releases
        run: |
          zip ./target/bundled/beatrec-${{ github.ref_name }}-${{ matrix.name }}-clap.zip ./target/bundled/beatrec.clap &&
          zip ./target/bundled/beatrec-${{ github.ref_name }}-${{ matrix.name }}-vst3.zip ./target/bundled/beatrec.vst3

      - name: Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.BEATREC_PAT }}
        run: |
          gh release upload ${{ github.ref_name }} \
          ./target/bundled/beatrec-${{ github.ref_name }}-${{ matrix.name }}-clap.zip#Beatrec\ ${{ github.ref_name }}\ \(CLAP,\ ${{ matrix.name }}) \
          ./target/bundled/beatrec-${{ github.ref_name }}-${{ matrix.name }}-vst3.zip#Beatrec\ ${{ github.ref_name }}\ \(VST3,\ ${{ matrix.name }})
